# Generated by Django 3.2.25 on 2025-04-27 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
