# Generated by Django 3.2.25 on 2025-04-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
    ]
