# Generated by Django 3.2.25 on 2025-04-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_training_trainingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.utilisateur'),
        ),
    ]
