# Generated by Django 3.2.25 on 2025-05-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_contactmessage_contact'),
        ('pages', '0008_employe_utilisateur'),
    ]

    operations = [
    ]
