# Generated by Django 3.2.25 on 2025-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_merge_20250504_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], default='CDI', max_length=50),
        ),
    ]
