# Generated by Django 3.2.25 on 2025-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_contrat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='contract_id',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Identifiant du contrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='leave_entitlement',
            field=models.IntegerField(default=25, verbose_name='Jours de congé annuels'),
        ),
    ]
