# Generated by Django 3.2.25 on 2025-05-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20250513_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='salaire_initial',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='type',
        ),
    ]
