# Generated by Django 3.2.25 on 2025-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20250513_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='type',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], default='CDI', max_length=50, verbose_name='Type de contrat'),
        ),
    ]
