# Generated by Django 3.2.25 on 2025-05-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_contrat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='competences_requises',
            field=models.TextField(blank=True, help_text='Compétences requises pour le poste.', null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire',
            field=models.CharField(blank=True, help_text='Salaire proposé (ex. 30k-40k EUR/an).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='date_expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.departement'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='statut',
            field=models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
